version: "3.7"
services:
  db:
    container_name: mysql
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/conf:/etc/mysql/conf.d
      - ./mysql/db:/var/lib/mysql
  php:
    container_name: php
    build: ./php-fpm
    volumes:
      - ./src:/usr/share/nginx/html
  server:
    container_name: nginx
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/usr/share/nginx/html
      - ./site.conf:/etc/nginx/conf.d/default.conf